enabled_materials:
  - OAK_SIGN
  - OAK_WALL_SIGN
  - SPRUCE_SIGN
  - SPRUCE_WALL_SIGN
  - BIRCH_SIGN
  - BIRCH_WALL_SIGN
  - JUNGLE_SIGN
  - JUNGLE_WALL_SIGN
  - ACACIA_SIGN
  - ACACIA_WALL_SIGN
  - DARK_OAK_SIGN
  - DARK_OAK_WALL_SIGN
  - CRIMSON_SIGN
  - CRIMSON_WALL_SIGN
  - WARPED_SIGN
  - WARPED_WALL_SIGN